/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.vendor.adbmanager;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int btn_disable=0x7f020000;
        public static final int btn_enable=0x7f020001;
        public static final int btn_rounded=0x7f020002;
        public static final int card_bg=0x7f020003;
        public static final int divider=0x7f020004;
        public static final int ic_gear=0x7f020005;
        public static final int status_circle=0x7f020006;
        public static final int status_circle_red=0x7f020007;
    }
    public static final class id {
        public static final int btn_exit=0x7f060011;
        public static final int btn_gen_pair=0x7f06000b;
        public static final int btn_mobile_data=0x7f06000d;
        public static final int btn_toggle_adb=0x7f060004;
        public static final int btn_usb2_power=0x7f06000e;
        public static final int btn_usb31_power=0x7f06000f;
        public static final int btn_usb32_power=0x7f060010;
        public static final int btn_wireless_disable=0x7f060008;
        public static final int btn_wireless_enable=0x7f060007;
        public static final int status_indicator=0x7f060000;
        public static final int tv_ip_port=0x7f060006;
        public static final int tv_mobile_status=0x7f06000c;
        public static final int tv_pair_code=0x7f060009;
        public static final int tv_pair_port=0x7f06000a;
        public static final int tv_status=0x7f060001;
        public static final int tv_subtitle=0x7f060002;
        public static final int tv_uid=0x7f060003;
        public static final int tv_wireless_status=0x7f060005;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
    public static final class style {
        public static final int AppTheme=0x7f050000;
    }
}